---
- name: install Nginx Package
  yum: name=nginx state=present

- name: copy nginx default.conf
  template:
    src=default.conf  dest=/etc/nginx/conf.d/default.conf
  notify: reload nginx

- name: copy nginx nginx.conf
  template:
    src=nginx.conf dest=/etc/nginx/nginx.conf
  notify: reload nginx

- name: start nginx and enabled
  service: name=nginx state=started enabled=yes

