---
- name: install nginx 
  yum: name=nginx state=present

- name: copy first page
  copy: src=/root/role/nginx/files/index.html dest=/usr/share/nginx/html/index.html

- name: copy nginx.conf
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
  notify: reload nginx

- name: copy default.conf
  template: src=default.conf.j2 dest=/etc/nginx/conf.d/default.conf
  notify: reload nginx

- name: reload nginx
  service: name=nginx state=started enabled=yes

